// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX6hObBZHt6eMXlHCLriOy7P-FQLohjb4',
    appId: '1:674663446479:web:dba9f6dba9ed2f8c7644ba',
    messagingSenderId: '674663446479',
    projectId: 'avira-suite',
    authDomain: 'avira-suite.firebaseapp.com',
    storageBucket: 'avira-suite.firebasestorage.app',
    measurementId: 'G-PXGD9KRVTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJc9pbTYIpc38z_uQk9khEszFoM0Oro-M',
    appId: '1:674663446479:android:7e990533836acc127644ba',
    messagingSenderId: '674663446479',
    projectId: 'avira-suite',
    storageBucket: 'avira-suite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Ow8AS_pFgC8RorhomUK7HVk0w1xYj-w',
    appId: '1:674663446479:ios:0cd882661decf6447644ba',
    messagingSenderId: '674663446479',
    projectId: 'avira-suite',
    storageBucket: 'avira-suite.firebasestorage.app',
    iosBundleId: 'com.example.averraSuite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Ow8AS_pFgC8RorhomUK7HVk0w1xYj-w',
    appId: '1:674663446479:ios:0cd882661decf6447644ba',
    messagingSenderId: '674663446479',
    projectId: 'avira-suite',
    storageBucket: 'avira-suite.firebasestorage.app',
    iosBundleId: 'com.example.averraSuite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX6hObBZHt6eMXlHCLriOy7P-FQLohjb4',
    appId: '1:674663446479:web:02ba59463210e5737644ba',
    messagingSenderId: '674663446479',
    projectId: 'avira-suite',
    authDomain: 'avira-suite.firebaseapp.com',
    storageBucket: 'avira-suite.firebasestorage.app',
    measurementId: 'G-R4B3RHFYEW',
  );
}
